// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqaPA7G_fwhWLgj_xr-zyau89mwP2YcCE',
    appId: '1:359392356146:web:ae78475476b275db6d192b',
    messagingSenderId: '359392356146',
    projectId: 'chatapi-f309d',
    authDomain: 'chatapi-f309d.firebaseapp.com',
    storageBucket: 'chatapi-f309d.appspot.com',
    measurementId: 'G-RQJNJ4XXHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIk15r_Pa8DlD-SCN99oCchJIYdadQjc',
    appId: '1:359392356146:android:4bd098e7199111736d192b',
    messagingSenderId: '359392356146',
    projectId: 'chatapi-f309d',
    storageBucket: 'chatapi-f309d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneoo392asSRAArErPgD_wzn7JOt6SBSc',
    appId: '1:359392356146:ios:2a1104d456fd1b0c6d192b',
    messagingSenderId: '359392356146',
    projectId: 'chatapi-f309d',
    storageBucket: 'chatapi-f309d.appspot.com',
    iosBundleId: 'com.example.chatTerra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneoo392asSRAArErPgD_wzn7JOt6SBSc',
    appId: '1:359392356146:ios:2a1104d456fd1b0c6d192b',
    messagingSenderId: '359392356146',
    projectId: 'chatapi-f309d',
    storageBucket: 'chatapi-f309d.appspot.com',
    iosBundleId: 'com.example.chatTerra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqaPA7G_fwhWLgj_xr-zyau89mwP2YcCE',
    appId: '1:359392356146:web:7d6198ca6fa4122a6d192b',
    messagingSenderId: '359392356146',
    projectId: 'chatapi-f309d',
    authDomain: 'chatapi-f309d.firebaseapp.com',
    storageBucket: 'chatapi-f309d.appspot.com',
    measurementId: 'G-301ND08EB0',
  );

}